### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by streunerlein** [komola/paymill-node#14]
Hi there

can you publish the latest changes to npm registry? My app just broke because i used `preauthorizations.remove`, which isnt in the 0.0.4 npm package.

Greetings

**Comment by paymill-support** [comment]
Please enter your answer above the separator

Request received: [paymill-node] Publish to npm (#14) (Ticket Nr. #25268)

Hello komola/paymill-node!

Thank you for your request and interest in PAYMILL! 

We are very happy to help you and will get back to you within 24hours.

We have a FAQ section on our website you can look up in the meantime - https://paymill.zendesk.com/hc/en-us

Also we value any kind of comments or concerns, if you are up for a chat or discussion, please follow us on twitter www.twitter.com/paymill and Facebook www.facebook.com/paymill or have a look into our blog at https://blog.paymill.com/.

For updates on operations (such as our maintenance schedule) please look up https://twitter.com/PAYMILLOps.

Best

The PAYMILL Team

###

## https://support.paymill.com/hc/requests/25268

komola/paymill-node, Dec 29 17:38

Hi there

can you publish the latest changes to npm registry? My app just broke because i used `preauthorizations.remove`, which isnt in the 0.0.4 npm package.

Greetings

---

Reply to this email directly or view it on GitHub:
https://github.com/komola/paymill-node/issues/14

---

This email is a service from PAYMILL GmbH Support.

[M6WP-76Z6]

**Comment by thomaschaaf** [comment]
Done

**Comment by streunerlein** [comment]
hardcore. Thanks!

**Comment by paymill-support** [comment]
Please enter your answer above the separator

Anfrage Nr. #25268: Wie würden Sie den erhaltenen Support bewerten?

Hello komola/paymill-node,

We would like to know what you think of our customer service. Please take a moment to answer the following short question:

How would you rate the support you received?

You can copy the following URL into your browser to rate:

  https://support.paymill.com/requests/25268/satisfaction/new/lpkisC5xTzCYlfhkNFNCLjaOb?locale=1

On your ticket was the following topic:

---

komola/paymill-node, December 29, 2013 18:51

hardcore. Thanks!

---

Reply to this email directly or view it on GitHub:
https://github.com/komola/paymill-node/issues/14#issuecomment-31321532

---

komola/paymill-node, December 29, 2013 18:14

Done

---

Reply to this email directly or view it on GitHub:
https://github.com/komola/paymill-node/issues/14#issuecomment-31320777

---

komola/paymill-node, December 29, 2013 18:14

Closed #14.

---

Reply to this email directly or view it on GitHub:
https://github.com/komola/paymill-node/issues/14

---

komola/paymill-node, December 29, 2013 17:38

Hi there

can you publish the latest changes to npm registry? My app just broke because i used `preauthorizations.remove`, which isnt in the 0.0.4 npm package.

Greetings

---

Reply to this email directly or view it on GitHub:
https://github.com/komola/paymill-node/issues/14

---

This email is a service from PAYMILL GmbH Support.

[M6WP-76Z6]
